### ISSUE TITLE
Не выводится название для неизвестных портов

### ISSUE THREAD

**Issue by Player701** [LPDem/UDoomLauncher#2]
![изображение](https://user-images.githubusercontent.com/9046118/56098703-988a7300-5f0b-11e9-8d8b-5c81eb744df4.png)
Если в свойствах ничего нет, следует выводить хотя бы имя файла. Скачать порт для проверки можно здесь: https://sourceforge.net/projects/prboom-plus/

**Comment by LPDem** [comment]
1.4
