### ISSUE TITLE
Если значение для числового параметра не задано, то используется 0

### ISSUE THREAD

**Issue by Player701** [LPDem/UDoomLauncher#5]
Если стереть значение числового параметра, строка останется пустой, а значение, передаваемое при запуске, станет равным 0. Нужно, чтобы в случае стирания значения возвращалось либо значение, установленное в последний раз, либо значение по умолчанию. Предпочтительно первое.

**Comment by LPDem** [comment]
Сделал возврат значения по умолчанию, всё же так правильнее.
v.1.7

**Comment by Player701** [comment]
Ок. Спасибо
